import {useState} from 'react'
import {useSavedState} from '../hooks/useSavedState'
import {Card,Heading} from './UI'
export default function CustomWellness({water,setWater,waterGoal,setWaterGoal,sleep,setSleep,sleepGoal,setSleepGoal,workouts,setWorkouts}){
 const [amount,setAmount]=useState(250),[editWater,setEditWater]=useState(false),[editSleep,setEditSleep]=useState(false),[draft,setDraft]=useState(null)
 const [waterDraft,setWaterDraft]=useState(waterGoal),[sleepDraft,setSleepDraft]=useState(sleepGoal)
 const [history,setHistory]=useSavedState('workout-history',[])
 function saveWorkout(e){e.preventDefault();if(!draft.title.trim())return;setWorkouts(old=>draft.id?old.map(w=>w.id===draft.id?draft:w):[...old,{...draft,id:crypto.randomUUID(),done:false}]);setDraft(null)}
 function complete(w){const done=!w.done;setWorkouts(old=>old.map(x=>x.id===w.id?{...x,done}:x));setHistory(old=>done?[...old.filter(x=>x.id!==w.id),{...w,done:true,date:new Date().toLocaleString()}]:old.filter(x=>x.id!==w.id))}
 return <section id="wellness" className="wellness-grid"><Card><Heading title="Stay hydrated"><button className="edit-button" onClick={()=>{setWaterDraft(waterGoal);setEditWater(!editWater)}}>Edit goal</button></Heading><div className="wellness-number">{(water/1000).toFixed(2)}<small> / {waterGoal/1000} L</small></div><p className="caption">{water>=waterGoal?'Goal reached':`${waterGoal-water} ml remaining`}</p><div className="meter"><i style={{width:`${Math.min(100,water/waterGoal*100)}%`}}/></div>{editWater&&<form className="editor-form" onSubmit={e=>{e.preventDefault();setWaterGoal(Number(waterDraft));setEditWater(false)}}><label>Daily water goal (ml)<input type="number" min="1" step="1" required value={waterDraft} onChange={e=>setWaterDraft(e.target.value)}/></label><button className="primary">Save goal</button></form>}<label className="inline-field">Drink amount (ml)<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="editor-actions"><button className="soft-button" disabled={!Number.isInteger(Number(amount))||Number(amount)<=0} onClick={()=>setWater(water+Number(amount))}>+ Log water</button><button className="edit-button" onClick={()=>setWater(0)}>Reset intake</button></div><label className="inline-field">Edit total intake (ml)<input type="number" min="0" step="1" value={water} onChange={e=>{if(e.target.value!==''&&Number(e.target.value)>=0)setWater(Number(e.target.value))}}/></label></Card>
 <Card><Heading title="Get moving"><button className="edit-button" onClick={()=>setDraft({title:'',minutes:45})}>+ Add workout</button></Heading><p className="caption">{workouts.filter(w=>w.done).reduce((s,w)=>s+Number(w.minutes),0)} minutes completed</p>{workouts.map(w=><div className="workout-edit-row" key={w.id}><label><input type="checkbox" checked={w.done} onChange={()=>complete(w)}/>{w.title} · {w.minutes} min</label><div><button className="edit-button" onClick={()=>setDraft({...w})}>Edit</button><button className="edit-button" onClick={()=>{setWorkouts(old=>old.filter(x=>x.id!==w.id));setHistory(old=>old.filter(x=>x.id!==w.id))}}>Delete</button></div></div>)}{!workouts.length&&<p className="caption">Add a workout to plan your activity.</p>}{draft&&<form className="editor-form" onSubmit={e=>{saveWorkout(e);if(draft.id)setHistory(old=>old.map(x=>x.id===draft.id?{...x,...draft}:x))}}><label>Workout name<input required maxLength={100} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Duration (minutes)<input required type="number" min="1" step="1" value={draft.minutes} onChange={e=>setDraft({...draft,minutes:Number(e.target.value)})}/></label><div className="editor-actions"><button className="primary">Save workout</button><button className="edit-button" type="button" onClick={()=>setDraft(null)}>Cancel</button></div></form>}<details className="activity-history"><summary>Saved workout activity ({history.length})</summary>{history.map(w=><div key={w.id}><p>{w.title} · {w.minutes} min</p><small>{w.date}</small><button className="edit-button" onClick={()=>{setHistory(old=>old.filter(x=>x.id!==w.id));setWorkouts(old=>old.map(x=>x.id===w.id?{...x,done:false}:x))}}>Delete activity</button></div>)}</details></Card>
 <Card><Heading title="Rest & recharge"><button className="edit-button" onClick={()=>{setSleepDraft(sleepGoal);setEditSleep(!editSleep)}}>Edit goal</button></Heading><div className="wellness-number">{sleep}<small> / {sleepGoal} hrs</small></div>{editSleep&&<form className="editor-form" onSubmit={e=>{e.preventDefault();setSleepGoal(Number(sleepDraft));setEditSleep(false)}}><label>Sleep goal (hours)<input required type="number" min="0.5" max="24" step="0.5" value={sleepDraft} onChange={e=>setSleepDraft(e.target.value)}/></label><button className="primary">Save goal</button></form>}<label className="inline-field">Hours slept<input type="number" min="0" max="24" step="0.5" value={sleep} onChange={e=>{if(e.target.value!==''&&Number(e.target.value)>=0&&Number(e.target.value)<=24)setSleep(Number(e.target.value))}}/></label><button className="edit-button" onClick={()=>setSleep(0)}>Clear sleep log</button></Card></section>
}
