import WaterTracker from './WaterTracker'
import {weekDates} from '../data/calendar'
import {useState} from 'react'
import {Card,Heading,Icon} from './UI'
export function Tasks({tasks,setTasks}){
 const [filter,setFilter]=useState('All'),[title,setTitle]=useState(''),[priority,setPriority]=useState('Medium')
 const visible=tasks.filter(t=>filter==='All'||(filter==='Completed'?t.done:!t.done))
 function add(e){e.preventDefault();if(!title.trim())return;setTasks([...tasks,{id:crypto.randomUUID(),title:title.trim(),category:'Personal',priority,done:false}]);setTitle('');setFilter('All')}
 return <Card id="tasks"><Heading title="Today’s tasks" subtitle="A clear plan. A little less mental clutter."><span className="badge">{tasks.filter(t=>t.done).length}/{tasks.length}</span></Heading><div className="tabs" aria-label="Filter tasks">{['All','Pending','Completed'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="task-list">{!visible.length&&<p className="empty">{filter==='Pending'?'All caught up. Enjoy the breathing room.':'No tasks here yet.'}</p>}{visible.map(t=><div className={`task-row ${t.done?'done':''}`} key={t.id}><label className="task-label"><input type="checkbox" checked={t.done} onChange={()=>setTasks(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><span><strong>{t.title}</strong><small>{t.category}</small></span></label><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span><button className="icon-button delete-task" aria-label={`Delete ${t.title}`} onClick={()=>setTasks(tasks.filter(x=>x.id!==t.id))}><Icon name="trash" size={16}/></button></div>)}</div><form className="task-form" onSubmit={add}><Icon name="plus" size={18}/><input id="task-title" aria-label="New task title" placeholder="What would you like to get done?" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={160}/><select aria-label="New task priority" value={priority} onChange={e=>setPriority(e.target.value)}>{['Low','Medium','High'].map(p=><option key={p}>{p}</option>)}</select><button className="add-button" aria-label="Add task"><Icon name="arrow" size={18}/></button></form></Card>
}
export function Habits({habits,setHabits,history}){const [adding,setAdding]=useState(false),[name,setName]=useState('');return <Card id="habits"><Heading title="Build your rhythm" subtitle="Habits that make the difference."><button className="icon-button" aria-label="Add habit" onClick={()=>setAdding(!adding)}><Icon name="plus"/></button></Heading><div className="habit-list">{habits.map(h=><div className="habit-row" key={h.id}><span className={`habit-icon ${h.done?'checked':''}`}><Icon name={h.icon}/></span><div className="habit-copy"><strong>{h.title}</strong><small>{h.subtitle}</small></div><span className="habit-streak" title="Consecutive days completed"><Icon name="flame" size={14}/>{history?.habitStreaks?.[h.id]??0}</span><input type="checkbox" aria-label={`Complete ${h.title}`} checked={h.done} onChange={()=>setHabits(habits.map(x=>x.id===h.id?{...x,done:!x.done}:x))}/></div>)}</div>{adding&&<form className="task-form" onSubmit={e=>{e.preventDefault();if(!name.trim())return;setHabits([...habits,{id:crypto.randomUUID(),title:name.trim(),subtitle:'Your daily habit',icon:'check',done:false,streak:0}]);setName('');setAdding(false)}}><input autoFocus aria-label="New habit name" placeholder="Name your new habit…" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><button className="add-button" aria-label="Save habit"><Icon name="check" size={18}/></button><button className="undo-button" type="button" onClick={()=>setAdding(false)}>Cancel</button></form>}<div className="habit-summary"><span>{habits.filter(h=>h.done).length} of {habits.length} habits complete</span><span>You’ve got this ↗</span></div></Card>}
export function Wellness({water,setWater,waterGoal,setWaterGoal,workout,setWorkout,sleep,setSleep}){return <section id="wellness" className="wellness-grid" aria-label="Health and wellness"><WaterTracker {...{water,setWater,waterGoal,setWaterGoal}}/><Card><Heading title="Get moving"><span className="tile orange"><Icon name="activity"/></span></Heading><div className="wellness-number">{workout?'45':'0'}<small> / 45 min</small></div><p className="caption">Today’s plan · Full-body workout</p><div className="workout-plan"><span>Strength training</span><span>45 min</span></div><button className="soft-button" aria-pressed={workout} onClick={()=>setWorkout(!workout)}><Icon name="check" size={16}/>{workout?'Completed · Undo':'Mark workout complete'}</button></Card><Card><Heading title="Rest & recharge"><span className="tile purple"><Icon name="moon"/></span></Heading><div className="wellness-number">{sleep}<small> / 8 hrs</small></div><p className="caption">{sleep>=8?'Your sleep goal is met':'A rested mind goes further'}</p><label className="sleep-control"><span>Last night’s sleep <strong>{sleep} h</strong></span><input aria-label="Hours slept" type="range" min="0" max="12" step="0.5" value={sleep} onChange={e=>setSleep(Number(e.target.value))}/></label><div className="sleep-scale"><span>0 hours</span><span>12 hours</span></div></Card></section>}

export function Weekly({history}) {
 const [period,setPeriod]=useState('This week')
 const dates=weekDates(history?.day,period==='Last week')
 const values=dates.map(day=>history?.days.find(d=>d.day===day)?.score??null)
 const recorded=values.filter(v=>v!==null)
 return <Card id="weekly"><Heading title="Your week in motion" subtitle={history?`Recorded daily progress · ${history.zone}`:'Loading recorded history…'}><select aria-label="Chart period" value={period} onChange={e=>setPeriod(e.target.value)}><option>This week</option><option>Last week</option></select></Heading><div className="chart-summary"><strong>{recorded.length?Math.round(recorded.reduce((a,b)=>a+b,0)/recorded.length):'—'}<small>%</small></strong><span>average of recorded days</span></div>{!recorded.length&&<p>No activity recorded for this week yet.</p>}<div className="chart"><div className="chart-axis"><span>100%</span><span>50%</span><span>0%</span></div><div className="chart-plot">{values.map((value,i)=><div className="chart-column" key={dates[i]}><div className="bar-space"><div className={`bar ${dates[i]===history?.day?'today':''}`} style={{height:`${value??0}%`}}>{value!==null&&<span>{value}%</span>}</div>{value===null&&<span>—</span>}</div><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>)}</div></div></Card>
}

